import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import Logout from "./components/Auth/Logout";
import { UserProvider } from "./context/UserContext";
import { TokenProvider } from "./context/TokenContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <TokenProvider>
            <UserProvider>
              <Logout />
              {children}
            </UserProvider>
          </TokenProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
