import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainSidebar from "../components/Common/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <MainSidebar />
      <div className="">{children}</div>
    </div>
  );
}
